# Generated by Django 3.1.5 on 2022-08-22 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='number',
        ),
        migrations.AddField(
            model_name='players',
            name='nationality',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='players',
            name='player_foot',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='players',
            name='player_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='player_id',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='players',
            name='team',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='players',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='players',
            name='position',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(default=None, max_length=100)),
                ('name', models.CharField(default=None, max_length=100)),
                ('logo', models.URLField(default=None, max_length=500)),
                ('coach', models.CharField(default=None, max_length=100)),
                ('asst_coach', models.CharField(default=None, max_length=100)),
                ('club', models.CharField(default=None, max_length=100)),
                ('country', models.CharField(default=None, max_length=100)),
                ('city', models.CharField(default=None, max_length=100)),
                ('team_short_name', models.CharField(default=None, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
