# Generated by Django 3.1.5 on 2022-08-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220822_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('tournament_id', models.CharField(default=None, max_length=100)),
                ('type', models.CharField(default=None, max_length=100)),
                ('country', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
