# Generated by Django 3.1.5 on 2022-08-23 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220823_1403'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
