# Generated by Django 3.1.5 on 2022-08-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='first_half',
            field=models.URLField(default=None, max_length=2000),
        ),
        migrations.AddField(
            model_name='match',
            name='full_match',
            field=models.URLField(default=None, max_length=2000),
        ),
        migrations.AddField(
            model_name='match',
            name='opponent_goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='opponent_icon',
            field=models.URLField(default=None, max_length=2000),
        ),
        migrations.AddField(
            model_name='match',
            name='second_half',
            field=models.URLField(default=None, max_length=2000),
        ),
    ]
