# Generated by Django 3.1.5 on 2022-08-25 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220824_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(default=None, max_length=100)),
                ('team', models.CharField(default=None, max_length=100)),
                ('player_foot', models.CharField(default=None, max_length=100)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.match')),
            ],
        ),
    ]
