# Generated by Django 3.1.5 on 2022-08-25 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_performace'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Performace',
        ),
    ]
