# Generated by Django 3.1.5 on 2022-08-26 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_performance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='user',
        ),
    ]
