# Generated by Django 3.1.5 on 2022-08-26 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_performance_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='assists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='performance',
            name='corners',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='performance',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='performance',
            name='fouls_commited',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='performance',
            name='freekicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='performance',
            name='penalties_scored',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='performance',
            name='penalties_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='performance',
            name='position',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='performance',
            name='recovered_balls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='performance',
            name='reds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='performance',
            name='tackles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='performance',
            name='tackles_accuracy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='performance',
            name='tournament',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='performance',
            name='yellows',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performance',
            name='goals',
            field=models.IntegerField(default=0),
        ),
    ]
