# Generated by Django 3.1.5 on 2022-08-26 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_performance_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='match',
        ),
    ]
