# Generated by Django 3.1.5 on 2022-08-26 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_performance_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='match',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.match'),
        ),
    ]
