# Generated by Django 3.1.5 on 2022-08-26 09:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0022_performance_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(default=None, max_length=2000)),
                ('type', models.CharField(default=None, max_length=150)),
                ('opponent', models.CharField(default=None, max_length=200)),
                ('tournament', models.CharField(default=None, max_length=200)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('match', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.match')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
