# Generated by Django 4.0.7 on 2022-08-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='wl',
            field=models.CharField(default=None, max_length=4),
        ),
    ]
