# Generated by Django 4.0.7 on 2022-08-31 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_video_wl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='wl',
            new_name='win_lose',
        ),
    ]
