# Generated by Django 4.0.7 on 2022-09-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_match_away_corners_match_away_cross_match_away_fouls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='date',
            field=models.DateField(default=None, verbose_name='Date'),
        ),
    ]
