# Generated by Django 4.0.7 on 2022-09-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_performance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_shotoff',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='away_shoton',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='home_shotoff',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='home_shoton',
            field=models.IntegerField(default=0),
        ),
    ]
