# Generated by Django 4.0.7 on 2022-09-19 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_match_away_shotoff_match_away_shoton_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='away_shotoff',
            new_name='away_shots',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='home_shotoff',
            new_name='home_shots',
        ),
    ]
