# Generated by Django 4.0.7 on 2022-10-02 22:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0029_rename_away_shotoff_match_away_shots_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('video', models.URLField(default=None, max_length=2000)),
                ('tournament_name', models.CharField(default=None, max_length=1000)),
                ('season', models.CharField(default=None, max_length=500)),
                ('match_no', models.CharField(default=None, max_length=100)),
                ('raider_name', models.CharField(default=None, max_length=500)),
                ('number_of_defender', models.CharField(default=None, max_length=100)),
                ('outcome', models.CharField(default=None, max_length=500)),
                ('raiding_team_points', models.CharField(default=None, max_length=100)),
                ('bonus', models.CharField(default=None, max_length=300)),
                ('raiding_team_name', models.CharField(default=None, max_length=100)),
                ('defending_team_name', models.CharField(default=None, max_length=300)),
                ('attacking_skills', models.CharField(default=None, max_length=300)),
                ('defensive_skills', models.CharField(default=None, max_length=300)),
                ('counter_action_skills', models.CharField(default=None, max_length=300)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
